name: CI/CD
on:
  push:

env:
  FORCE_COLOR: 3

# Cancel in-progress runs on new updates,
# except for deployment runs which could
# leave the app in an inconsistent state.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != 'main' && github.ref_name != 'beta' }}

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test

      - name: Type checking
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test CLI
        env:
          # Use the non-regression test main secret
          MAIN_SECRET: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
        run: |
          node ./dist/cli.cjs generate
          node ./dist/cli.cjs encrypt -c ci -a aes-256-gcm < cleartext.bin > ciphertext.ci.aes-256-gcm.bin
          node ./dist/cli.cjs encrypt -c ci -a chacha20-poly1305 < cleartext.bin > ciphertext.ci.chacha20-poly1305.bin
          node ./dist/cli.cjs decrypt -c ci < ciphertext.ci.aes-256-gcm.bin > cleartext.ci.aes-256-gcm.bin
          node ./dist/cli.cjs decrypt -c ci < ciphertext.ci.chacha20-poly1305.bin > cleartext.ci.chacha20-poly1305.bin
          node ./dist/cli.cjs decrypt -c context < ciphertext.aes-256-gcm.bin > cleartext.aes-256-gcm.bin
          node ./dist/cli.cjs decrypt -c context < ciphertext.chacha20-poly1305.bin > cleartext.chacha20-poly1305.bin
          diff cleartext.bin cleartext.ci.aes-256-gcm.bin
          diff cleartext.bin cleartext.ci.chacha20-poly1305.bin
          diff cleartext.bin cleartext.aes-256-gcm.bin
          diff cleartext.bin cleartext.chacha20-poly1305.bin

  # ----------------------------------------------------------------------------

  cd-npm:
    name: Release (NPM)
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ github.ref_name == 'main' || github.ref_name == 'beta' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      # Note: we do not use an external Turbo cache for publishing
      # to prevent against possible cache collision attacks.

      - name: Install dependencies
        run: pnpm install

      # NPM publish --

      - name: Build
        run: pnpm build

      - name: Publish (NPM)
        run: npx semantic-release
        env:
          SCEAU_PRIVATE_KEY: ${{ secrets.SCEAU_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN}}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
